import { Appointment, InventoryItem, UserProfile } from '../types';

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'user-admin-default',
    email: 'admin@homoeo.com',
    full_name: 'Md Abutalha Khan',
    role: 'admin',
    phone: '9933506514',
  },
  {
    id: 'user-admin-1',
    email: 'admin@homoeohealthcare.com',
    full_name: 'Md Abutalha Khan',
    role: 'admin',
    phone: '9933506514',
  },
  {
    id: 'user-doc-1',
    email: 'dr.haque@homoeohealthcare.com',
    full_name: 'Dr. M. A. Haque, M.D. (Homoeo)',
    role: 'doctor',
    phone: '9933506514',
  },
  {
    id: 'user-staff-1',
    email: 'reception@homoeohealthcare.com',
    full_name: 'Clinic Front Desk Staff',
    role: 'staff',
    phone: '9933506514',
  },
];

// Pure empty array - strictly no hardcoded mock patients
export const INITIAL_APPOINTMENTS: Appointment[] = [];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-001',
    medicine_name: 'Arnica Montana',
    category: 'Dilution',
    potency: '200C',
    bottle_size: '30 ml',
    rack_location: 'Rack A-01',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-01-10',
    expiry_date: '2029-01-10',
    mrp: 110,
    purchase_cost: 75,
    stock_quantity: 18,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-002',
    medicine_name: 'Arnica Montana',
    category: 'Dilution',
    potency: '1M',
    bottle_size: '30 ml',
    rack_location: 'Rack A-02',
    company: 'Dr. Reckeweg (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-11-05',
    expiry_date: '2028-11-05',
    mrp: 230,
    purchase_cost: 165,
    stock_quantity: 4, // Trigger low stock alert (<5)
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-003',
    medicine_name: 'Rhus Toxicodendron',
    category: 'Dilution',
    potency: '30C',
    bottle_size: '100 ml',
    rack_location: 'Rack A-08',
    company: 'Schwabe India (WSI)',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-03-12',
    expiry_date: '2029-03-12',
    mrp: 185,
    purchase_cost: 130,
    stock_quantity: 12,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-004',
    medicine_name: 'Rhus Toxicodendron',
    category: 'Dilution',
    potency: '200C',
    bottle_size: '30 ml',
    rack_location: 'Rack A-09',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-02-15',
    expiry_date: '2029-02-15',
    mrp: 110,
    purchase_cost: 75,
    stock_quantity: 3, // Urgent low stock (<5)
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-005',
    medicine_name: 'Bryonia Alba',
    category: 'Dilution',
    potency: '200C',
    bottle_size: '30 ml',
    rack_location: 'Rack A-12',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-04-01',
    expiry_date: '2029-04-01',
    mrp: 110,
    purchase_cost: 75,
    stock_quantity: 14,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-006',
    medicine_name: 'Nux Vomica',
    category: 'Dilution',
    potency: '30C',
    bottle_size: '30 ml',
    rack_location: 'Rack B-03',
    company: 'Schwabe India (WSI)',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-01-20',
    expiry_date: '2029-01-20',
    mrp: 105,
    purchase_cost: 70,
    stock_quantity: 22,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-007',
    medicine_name: 'Nux Vomica',
    category: 'Dilution',
    potency: '200C',
    bottle_size: '30 ml',
    rack_location: 'Rack B-04',
    company: 'Dr. Reckeweg (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-09-10',
    expiry_date: '2028-09-10',
    mrp: 230,
    purchase_cost: 165,
    stock_quantity: 2, // Urgent low stock!
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-008',
    medicine_name: 'Crataegus Oxyacantha',
    category: 'Mother Tincture (Q)',
    potency: 'Q',
    bottle_size: '100 ml',
    rack_location: 'Rack MT-01',
    company: 'Schwabe India (WSI)',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-02-28',
    expiry_date: '2029-02-28',
    mrp: 260,
    purchase_cost: 180,
    stock_quantity: 9,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-009',
    medicine_name: 'Berberis Aquifolium',
    category: 'Mother Tincture (Q)',
    potency: 'Q',
    bottle_size: '100 ml',
    rack_location: 'Rack MT-03',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-05-10',
    expiry_date: '2029-05-10',
    mrp: 225,
    purchase_cost: 155,
    stock_quantity: 11,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-010',
    medicine_name: 'Ashwagandha (Withania Somnifera)',
    category: 'Mother Tincture (Q)',
    potency: 'Q',
    bottle_size: '450/500 ml',
    rack_location: 'Rack Godown-01',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-01',
    expiry_date: '2029-03-01',
    mrp: 750,
    purchase_cost: 520,
    stock_quantity: 6,
    low_stock_threshold: 3,
    storage_location: 'Godown / Storage Room',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-011',
    medicine_name: 'Five Phos 6X',
    category: 'Biochemic / Bio-combination',
    potency: '6X',
    bottle_size: '100g',
    rack_location: 'Rack Bio-02',
    company: 'Schwabe India (WSI)',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-03-15',
    expiry_date: '2029-03-15',
    mrp: 175,
    purchase_cost: 120,
    stock_quantity: 16,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-012',
    medicine_name: 'Calcarea Fluorica',
    category: 'Biochemic / Bio-combination',
    potency: '12X',
    bottle_size: '25g',
    rack_location: 'Rack Bio-05',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-01-18',
    expiry_date: '2029-01-18',
    mrp: 95,
    purchase_cost: 65,
    stock_quantity: 8,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-013',
    medicine_name: 'Silicea',
    category: 'Trituration',
    potency: '30X',
    bottle_size: '25g',
    rack_location: 'Rack Trit-01',
    company: 'Dr. Reckeweg (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-12-01',
    expiry_date: '2028-12-01',
    mrp: 190,
    purchase_cost: 135,
    stock_quantity: 3, // Low stock
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-014',
    medicine_name: 'Stobal Cough Syrup',
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '100 ml',
    rack_location: 'Rack Pat-01',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-04-10',
    expiry_date: '2027-04-10',
    mrp: 120,
    purchase_cost: 85,
    stock_quantity: 25,
    low_stock_threshold: 8,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-015',
    medicine_name: 'Liv-T Liver Tonic',
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '180 ml',
    rack_location: 'Rack Pat-02',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-20',
    expiry_date: '2027-03-20',
    mrp: 140,
    purchase_cost: 98,
    stock_quantity: 19,
    low_stock_threshold: 6,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
];
