import { Appointment, InventoryItem, UserProfile } from '../types';

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'user-admin-default',
    email: 'admin@homoeo.com',
    full_name: 'Md Abutalha Khan',
    role: 'admin',
    phone: '9933506514',
  },
  {
    id: 'user-admin-1',
    email: 'admin@homoeohealthcare.com',
    full_name: 'Md Abutalha Khan',
    role: 'admin',
    phone: '9933506514',
  },
  {
    id: 'user-doc-1',
    email: 'dr.haque@homoeohealthcare.com',
    full_name: 'Dr. M. A. Haque, M.D. (Homoeo)',
    role: 'doctor',
    phone: '9933506514',
  },
  {
    id: 'user-staff-1',
    email: 'reception@homoeohealthcare.com',
    full_name: 'Clinic Front Desk Staff',
    role: 'staff',
    phone: '9933506514',
  },
];

// Pure empty array - strictly no hardcoded mock patients
export const INITIAL_APPOINTMENTS: Appointment[] = [];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-001',
    medicine_name: 'Arnica Montana',
    category: 'Dilution',
    potency: '200C',
    bottle_size: '30 ml',
    rack_location: 'Rack A-01',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-01-10',
    expiry_date: '2029-01-10',
    mrp: 110,
    purchase_cost: 75,
    stock_quantity: 18,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-002',
    medicine_name: 'Arnica Montana',
    category: 'Dilution',
    potency: '1M',
    bottle_size: '30 ml',
    rack_location: 'Rack A-02',
    company: 'Dr. Reckeweg (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-11-05',
    expiry_date: '2028-11-05',
    mrp: 230,
    purchase_cost: 165,
    stock_quantity: 4, // Trigger low stock alert (<5)
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-003',
    medicine_name: 'Rhus Toxicodendron',
    category: 'Dilution',
    potency: '30C',
    bottle_size: '100 ml',
    rack_location: 'Rack A-08',
    company: 'Schwabe India (WSI)',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-03-12',
    expiry_date: '2029-03-12',
    mrp: 185,
    purchase_cost: 130,
    stock_quantity: 12,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-004',
    medicine_name: 'Rhus Toxicodendron',
    category: 'Dilution',
    potency: '200C',
    bottle_size: '30 ml',
    rack_location: 'Rack A-09',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-02-15',
    expiry_date: '2029-02-15',
    mrp: 110,
    purchase_cost: 75,
    stock_quantity: 3, // Urgent low stock (<5)
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-005',
    medicine_name: 'Bryonia Alba',
    category: 'Dilution',
    potency: '200C',
    bottle_size: '30 ml',
    rack_location: 'Rack A-12',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-04-01',
    expiry_date: '2029-04-01',
    mrp: 110,
    purchase_cost: 75,
    stock_quantity: 14,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-006',
    medicine_name: 'Nux Vomica',
    category: 'Dilution',
    potency: '30C',
    bottle_size: '30 ml',
    rack_location: 'Rack B-03',
    company: 'Schwabe India (WSI)',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-01-20',
    expiry_date: '2029-01-20',
    mrp: 105,
    purchase_cost: 70,
    stock_quantity: 22,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-007',
    medicine_name: 'Nux Vomica',
    category: 'Dilution',
    potency: '200C',
    bottle_size: '30 ml',
    rack_location: 'Rack B-04',
    company: 'Dr. Reckeweg (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-09-10',
    expiry_date: '2028-09-10',
    mrp: 230,
    purchase_cost: 165,
    stock_quantity: 2, // Urgent low stock!
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-008',
    medicine_name: 'Crataegus Oxyacantha',
    category: 'Mother Tincture (Q)',
    potency: 'Q',
    bottle_size: '100 ml',
    rack_location: 'Rack MT-01',
    company: 'Schwabe India (WSI)',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-02-28',
    expiry_date: '2029-02-28',
    mrp: 260,
    purchase_cost: 180,
    stock_quantity: 9,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-009',
    medicine_name: 'Berberis Aquifolium',
    category: 'Mother Tincture (Q)',
    potency: 'Q',
    bottle_size: '100 ml',
    rack_location: 'Rack MT-03',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-05-10',
    expiry_date: '2029-05-10',
    mrp: 225,
    purchase_cost: 155,
    stock_quantity: 11,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-010',
    medicine_name: 'Ashwagandha (Withania Somnifera)',
    category: 'Mother Tincture (Q)',
    potency: 'Q',
    bottle_size: '450/500 ml',
    rack_location: 'Rack Godown-01',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-01',
    expiry_date: '2029-03-01',
    mrp: 750,
    purchase_cost: 520,
    stock_quantity: 6,
    low_stock_threshold: 3,
    storage_location: 'Godown / Storage Room',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-011',
    medicine_name: 'Five Phos 6X',
    category: 'Biochemic / Bio-combination',
    potency: '6X',
    bottle_size: '100g',
    rack_location: 'Rack Bio-02',
    company: 'Schwabe India (WSI)',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-03-15',
    expiry_date: '2029-03-15',
    mrp: 175,
    purchase_cost: 120,
    stock_quantity: 16,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-012',
    medicine_name: 'Calcarea Fluorica',
    category: 'Biochemic / Bio-combination',
    potency: '12X',
    bottle_size: '25g',
    rack_location: 'Rack Bio-05',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-01-18',
    expiry_date: '2029-01-18',
    mrp: 95,
    purchase_cost: 65,
    stock_quantity: 8,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-013',
    medicine_name: 'Silicea',
    category: 'Trituration',
    potency: '30X',
    bottle_size: '25g',
    rack_location: 'Rack Trit-01',
    company: 'Dr. Reckeweg (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-12-01',
    expiry_date: '2028-12-01',
    mrp: 190,
    purchase_cost: 135,
    stock_quantity: 3, // Low stock
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-014',
    medicine_name: 'Stobal Cough Syrup',
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '100 ml',
    rack_location: 'Rack Pat-01',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-04-10',
    expiry_date: '2027-04-10',
    mrp: 120,
    purchase_cost: 85,
    stock_quantity: 25,
    low_stock_threshold: 8,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-015',
    medicine_name: 'Liv-T Liver Tonic',
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '180 ml',
    rack_location: 'Rack Pat-02',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-20',
    expiry_date: '2027-03-20',
    mrp: 140,
    purchase_cost: 98,
    stock_quantity: 19,
    low_stock_threshold: 6,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-01',
    medicine_name: "Bakson's Calculi Aid Drops",
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-03',
    company: "Bakson Drugs & Pharmaceuticals",
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-02-10',
    expiry_date: '2027-02-10',
    mrp: 165,
    purchase_cost: 115,
    stock_quantity: 16,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-02',
    medicine_name: 'SBL Clearstone Drops',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-04',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-01',
    expiry_date: '2027-03-01',
    mrp: 160,
    purchase_cost: 110,
    stock_quantity: 20,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-03',
    medicine_name: 'Dr. Reckeweg R27 (Renal Calculi)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '22 ml',
    rack_location: 'Rack Pat-05',
    company: 'Dr. Reckeweg & Co (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-11-15',
    expiry_date: '2028-11-15',
    mrp: 310,
    purchase_cost: 220,
    stock_quantity: 14,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-04',
    medicine_name: 'Adel 22 (Renelix Drops)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '20 ml',
    rack_location: 'Rack Pat-06',
    company: 'Adel Pekana (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-12-05',
    expiry_date: '2028-12-05',
    mrp: 335,
    purchase_cost: 240,
    stock_quantity: 11,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-05',
    medicine_name: 'Wheezal WL-14 (Renal Calculi)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-07',
    company: 'Wheezal Homoeo Pharma',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-01-25',
    expiry_date: '2027-01-25',
    mrp: 170,
    purchase_cost: 118,
    stock_quantity: 15,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-06',
    medicine_name: 'Schwabe Berberis Pentarkan',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-08',
    company: 'Dr. Willmar Schwabe',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-02-18',
    expiry_date: '2029-02-18',
    mrp: 220,
    purchase_cost: 155,
    stock_quantity: 12,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-07',
    medicine_name: 'Allen A56 Renal Calculi Drops',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-09',
    company: 'Allen Homoeo',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-10',
    expiry_date: '2027-03-10',
    mrp: 175,
    purchase_cost: 120,
    stock_quantity: 10,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-08',
    medicine_name: 'Medisynth Renal Forte',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-10',
    company: 'Medisynth Chemicals',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-02-05',
    expiry_date: '2027-02-05',
    mrp: 180,
    purchase_cost: 125,
    stock_quantity: 9,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-09',
    medicine_name: "Bakson's Prost Aid Drops",
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-11',
    company: "Bakson Drugs & Pharmaceuticals",
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-01-15',
    expiry_date: '2027-01-15',
    mrp: 175,
    purchase_cost: 120,
    stock_quantity: 14,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-10',
    medicine_name: 'SBL Prostonum Drops',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-12',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-05',
    expiry_date: '2027-03-05',
    mrp: 165,
    purchase_cost: 115,
    stock_quantity: 18,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-11',
    medicine_name: 'Dr. Reckeweg R25 (Prostate Drops)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '22 ml',
    rack_location: 'Rack Pat-13',
    company: 'Dr. Reckeweg & Co (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-10-20',
    expiry_date: '2028-10-20',
    mrp: 310,
    purchase_cost: 220,
    stock_quantity: 11,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-12',
    medicine_name: 'Adel 21 (Proscat Drops)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '20 ml',
    rack_location: 'Rack Pat-14',
    company: 'Adel Pekana (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-11-28',
    expiry_date: '2028-11-28',
    mrp: 335,
    purchase_cost: 240,
    stock_quantity: 8,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-13',
    medicine_name: 'Wheezal WL-30 (Prostate Drops)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-15',
    company: 'Wheezal Homoeo Pharma',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-02-14',
    expiry_date: '2027-02-14',
    mrp: 170,
    purchase_cost: 118,
    stock_quantity: 13,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-14',
    medicine_name: 'Schwabe Sabal Pentarkan',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-16',
    company: 'Dr. Willmar Schwabe',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-01-20',
    expiry_date: '2029-01-20',
    mrp: 220,
    purchase_cost: 155,
    stock_quantity: 10,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-15',
    medicine_name: 'Allen A44 Prostate Drops',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-17',
    company: 'Allen Homoeo',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-12',
    expiry_date: '2027-03-12',
    mrp: 175,
    purchase_cost: 120,
    stock_quantity: 7,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-16',
    medicine_name: "Bakson's Rheum Aid Syrup",
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '115 ml',
    rack_location: 'Rack Pat-18',
    company: "Bakson Drugs & Pharmaceuticals",
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-02-15',
    expiry_date: '2027-02-15',
    mrp: 155,
    purchase_cost: 108,
    stock_quantity: 18,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-17',
    medicine_name: 'SBL Orthomuv Syrup & Oil',
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '180 ml',
    rack_location: 'Rack Pat-19',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-08',
    expiry_date: '2027-03-08',
    mrp: 190,
    purchase_cost: 130,
    stock_quantity: 16,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-18',
    medicine_name: 'Dr. Reckeweg R11 (Lumbacon)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '22 ml',
    rack_location: 'Rack Pat-20',
    company: 'Dr. Reckeweg & Co (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-11-10',
    expiry_date: '2028-11-10',
    mrp: 310,
    purchase_cost: 220,
    stock_quantity: 14,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-19',
    medicine_name: 'Dr. Reckeweg R73 (Osteoarthritis)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '22 ml',
    rack_location: 'Rack Pat-21',
    company: 'Dr. Reckeweg & Co (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-12-12',
    expiry_date: '2028-12-12',
    mrp: 310,
    purchase_cost: 220,
    stock_quantity: 12,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-20',
    medicine_name: 'Adel 24 (Septonsil Joint Drops)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '20 ml',
    rack_location: 'Rack Pat-22',
    company: 'Adel Pekana (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2024-01-10',
    expiry_date: '2028-01-10',
    mrp: 335,
    purchase_cost: 240,
    stock_quantity: 9,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-21',
    medicine_name: 'Wheezal WL-35 (Rheumatic Drops)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-23',
    company: 'Wheezal Homoeo Pharma',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-02-22',
    expiry_date: '2027-02-22',
    mrp: 170,
    purchase_cost: 118,
    stock_quantity: 15,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-22',
    medicine_name: 'Medisynth Rheuma-Saj Forte',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-24',
    company: 'Medisynth Chemicals',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-01-18',
    expiry_date: '2027-01-18',
    mrp: 185,
    purchase_cost: 128,
    stock_quantity: 11,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-23',
    medicine_name: 'Schwabe Topi MP Gel / Bryorheum',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-25',
    company: 'Dr. Willmar Schwabe',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-02-10',
    expiry_date: '2029-02-10',
    mrp: 235,
    purchase_cost: 165,
    stock_quantity: 10,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-24',
    medicine_name: "Bakson's Gastro Aid Syrup",
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '115 ml',
    rack_location: 'Rack Pat-26',
    company: "Bakson Drugs & Pharmaceuticals",
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-15',
    expiry_date: '2027-03-15',
    mrp: 145,
    purchase_cost: 100,
    stock_quantity: 22,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-25',
    medicine_name: 'Dr. Reckeweg R5 (Gastreu)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '22 ml',
    rack_location: 'Rack Pat-27',
    company: 'Dr. Reckeweg & Co (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-11-20',
    expiry_date: '2028-11-20',
    mrp: 310,
    purchase_cost: 220,
    stock_quantity: 17,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-26',
    medicine_name: 'Dr. Reckeweg R37 (Colic Drops)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '22 ml',
    rack_location: 'Rack Pat-28',
    company: 'Dr. Reckeweg & Co (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-12-15',
    expiry_date: '2028-12-15',
    mrp: 310,
    purchase_cost: 220,
    stock_quantity: 13,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-27',
    medicine_name: 'SBL Nixocid Syrup',
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '115 ml',
    rack_location: 'Rack Pat-29',
    company: 'SBL Pvt Ltd',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-03-12',
    expiry_date: '2027-03-12',
    mrp: 140,
    purchase_cost: 98,
    stock_quantity: 24,
    low_stock_threshold: 6,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-28',
    medicine_name: 'Adel 5 (Apo-Stom Drops)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '20 ml',
    rack_location: 'Rack Pat-30',
    company: 'Adel Pekana (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2024-01-20',
    expiry_date: '2028-01-20',
    mrp: 335,
    purchase_cost: 240,
    stock_quantity: 10,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-29',
    medicine_name: 'Wheezal WL-13 (Gastritis Drops)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-31',
    company: 'Wheezal Homoeo Pharma',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-02-18',
    expiry_date: '2027-02-18',
    mrp: 170,
    purchase_cost: 118,
    stock_quantity: 14,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-30',
    medicine_name: 'Medisynth Jondila Sugar Free',
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '115 ml',
    rack_location: 'Rack Pat-32',
    company: 'Medisynth Chemicals',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-03-01',
    expiry_date: '2027-03-01',
    mrp: 160,
    purchase_cost: 112,
    stock_quantity: 16,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-31',
    medicine_name: "Bakson's Kof Aid Syrup",
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '115 ml',
    rack_location: 'Rack Pat-33',
    company: "Bakson Drugs & Pharmaceuticals",
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-02-28',
    expiry_date: '2027-02-28',
    mrp: 135,
    purchase_cost: 92,
    stock_quantity: 26,
    low_stock_threshold: 6,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-32',
    medicine_name: 'Dr. Reckeweg R8 / R9 (Jutussin)',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '22 ml',
    rack_location: 'Rack Pat-34',
    company: 'Dr. Reckeweg & Co (Germany)',
    distributor: 'National Pharma Distributors',
    mfg_date: '2023-11-05',
    expiry_date: '2028-11-05',
    mrp: 310,
    purchase_cost: 220,
    stock_quantity: 15,
    low_stock_threshold: 4,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-33',
    medicine_name: 'Wheezal De-Kof Syrup',
    category: 'Patent / Syrups / Drops',
    potency: 'Syrup',
    bottle_size: '115 ml',
    rack_location: 'Rack Pat-35',
    company: 'Wheezal Homoeo Pharma',
    distributor: 'Eastern Homoeo Agency',
    mfg_date: '2024-03-05',
    expiry_date: '2027-03-05',
    mrp: 130,
    purchase_cost: 88,
    stock_quantity: 19,
    low_stock_threshold: 5,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-pat-34',
    medicine_name: 'Allen A05 Cough Drops',
    category: 'Patent / Syrups / Drops',
    potency: 'Drops',
    bottle_size: '30 ml',
    rack_location: 'Rack Pat-36',
    company: 'Allen Homoeo',
    distributor: 'Bengal Homoeo Stores',
    mfg_date: '2024-02-12',
    expiry_date: '2027-02-12',
    mrp: 175,
    purchase_cost: 120,
    stock_quantity: 11,
    low_stock_threshold: 3,
    storage_location: 'Clinic Dispensing Shelf',
    updated_at: new Date().toISOString(),
  },
];
